cocktail-web v1
jamie2779/cocktail-web pull request #6
Opened 2024-12-05 05:45 UTC by LAPLACE4A

## 작업 내용
- cocktail-web v1

## 체크리스트
- [x] 주요 기능이 정상적으로 동작함
- [ ] 코드에 불필요한 주석이나 디버깅 흔적이 없음
- [ ] 기존 코드와 호환성에 문제가 없음
- [ ] 필요한 문서를 업데이트 함
- [ ] 민감한 정보(api키 등)가 포함되어 있지 않음

## 추가 설명(선택)
- 전반적인 기본 기능들 정상 동작하는 것 확인함.
- 현재 웹소켓으로 기기와 연결하는 부분과 기기 연결 테스트 부분 구현 안되어 있음
- 추가적으로 하면 좋을 것 중에 커스텀 칵테일 도수 계산이 있음
- 그리고 전체적으로 디자인이 통일되지 않은 api 요청 성공 메세지도 손보면 좋을 것 같음

2024-12-05 05:45 UTC, LAPLACE4A commented
@jamie2779 PTAL

2024-12-05 21:19 UTC, jamie2779 requested changes
적어둔거 확인해보고 고칠 수 있는 만큼 고쳐주셈

2024-12-05 21:19 UTC, jamie2779 commented on app/Admin/page.tsx
폴더명 Admin 이라서 라우터 제대로 작동 안하는듯, admin으로 수정 부탁

2024-12-05 21:19 UTC, jamie2779 commented on components/overlay/SelectMenu.tsx
> +        <OverlayMenu
OverlayMenu의 우측 마진이 없이 나옴, 아래 이미지 참고, 수정 부탁
![image](https://github.com/user-attachments/assets/62f7d109-c792-4499-94b7-14e6bc98aae9)

2024-12-05 21:19 UTC, jamie2779 commented on components/CustomCocktail.tsx
> +
커스텀 칵테일 30ml 단위로 수정할 수 있게 변경

2024-12-05 21:19 UTC, jamie2779 commented on components/CustomCocktail.tsx
> +        setOrderStatus("주문이 큐에 추가되었습니다!"); // 성공
주문 성공시 /queue 페이지로 리다이렉트

2024-12-05 21:19 UTC, jamie2779 commented on components/overlay/CompleteOverlay.tsx
> +          닫기
주문 성공시 /queue 페이지로 리다이렉트

2024-12-05 21:19 UTC, jamie2779 commented on app/Admin/page.tsx
> +        setAllDrinks([
드롭다운에 표시되는 음료 목록 고정되어있는거 같은데, /data/drink.json 내용으로 나오게 수정

2024-12-05 21:19 UTC, jamie2779 commented on app/Admin/page.tsx
> +      alert("Changes saved successfully!");
얘만 alert라서 어색함, 토스트 쓰면 좋을듯 안되면 말구

2024-12-05 21:19 UTC, jamie2779 commented on app/Admin/page.tsx
> +      alert("Failed to save changes.");
여기도 마찬가지 토스트 쓰면 좋을듯

2024-12-05 21:19 UTC, jamie2779 commented on components/overlay/PasswordOverlay.tsx
> +          <Input
엔터치면 handleConfirm되도록 해주면 좋을듯

2024-12-05 21:19 UTC, jamie2779 commented on components/CustomCocktail.tsx
> +        setOrderStatus("주문이 큐에 추가되었습니다!"); // 성공
0ml짜리 커스텀 칵테일 주문도 받아짐, 커스텀 칵테일 용량 0ml초과, 300ml 이하로 제한 로직 추가

2024-12-05 21:19 UTC, jamie2779 commented on components/MenuList.tsx
> +            <Menu
커스텀 칵테일이면 abv 표시 안하도록 수정
0%보여주는거 보다는 아애 안보여주는 것이 나을 듯

2024-12-05 21:19 UTC, jamie2779 commented on components/Setting.tsx
이 파일은 어디 쓰는 파일인지 모르겠어서,, 어디에 쓰였는지 좀 알려주라....

2024-12-10 02:35 UTC, LAPLACE4A commented on app/Admin/page.tsx
@jamie2779 https://github.com/jamie2779/cocktail-web/pull/6/commits/052c07388fd3c55ca07bd90dc7f0f8168ad72b43

2024-12-12 21:25 UTC, merged

2024-12-12 21:25 UTC, jamie2779 commented
나머지는 추후 고치는걸로 하고 머지 하겠음